import { Animal, Review } from "../../types/typings";

export const bestSellers = [
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 20,
    updatedCount: 1,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 20,
    updatedCount: 1,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 20,
    updatedCount: 1,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 20,
    updatedCount: 1,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,

    viewsCount: 20,
    updatedCount: 1,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 20,
    updatedCount: 1,
  },
];
export const animals: Animal[] = [
  {
    name: "Kucing Persia",
    rating: 5,
    price: 9000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-05-15"),
    reviewsCount: 9,
    soldCount: 10,
    viewsCount: 100,
    updatedCount: 2,
  },
  {
    name: "Anjing Shepherd",
    rating: 5,
    price: 8000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/dog-reseller.png",
    createdAt: new Date("2023-02-11"),
    reviewsCount: 20,
    soldCount: 10,
    viewsCount: 40,
    updatedCount: 1,
  },
  {
    name: "Anjing Husky",
    rating: 5,
    price: 2000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/dog-reseller.png",
    createdAt: new Date("2022-11-11"),
    reviewsCount: 44,
    soldCount: 10,

    viewsCount: 19,
    updatedCount: 3,
  },
  {
    name: "Kucing Sphynx",
    rating: 5,
    price: 4000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-12-15"),
    reviewsCount: 24,
    soldCount: 10,
    viewsCount: 55,
    updatedCount: 5,
  },
  {
    name: "Kucing Angola",
    rating: 5,
    price: 3000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2023-01-14"),
    reviewsCount: 20,
    soldCount: 2,
    viewsCount: 24,
    updatedCount: 2,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 5000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-08-11"),
    reviewsCount: 40,
    soldCount: 20,
    viewsCount:111,
    updatedCount:1
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 10000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2023-02-11"),
    reviewsCount: 55,
    soldCount: 43,
    viewsCount: 33,
    updatedCount: 0,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 8000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2023-03-04"),
    reviewsCount: 20,
    soldCount: 22,
    viewsCount:54,
    updatedCount:1
  },
  {
    name: "Anjing Shiba",
    rating: 5,
    price: 4000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/dog-reseller.png",
    createdAt: new Date("2023-03-02"),
    reviewsCount: 20,
    soldCount: 1,
    viewsCount: 44,
    updatedCount: 4,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 2000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 30,
    soldCount: 4,
    viewsCount: 23,
    updatedCount: 7,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 6000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-03-06"),
    reviewsCount: 10,
    soldCount: 22,

    viewsCount: 65,
    updatedCount: 8,
  },
  {
    name: "Kucing Persia",
    rating: 5,
    price: 3000000,
    remainingStock: 5,
    city: "Bandung",
    image: "/assets/cat-reseller.png",
    createdAt: new Date("2022-07-06"),
    reviewsCount: 60,
    soldCount: 30,
    viewsCount: 45,
    updatedCount: 2,
  },
];

export const ratingList = [
  {
    rating: 5,
    ratingCount: 98,
  },
  {
    rating: 4,
    ratingCount: 0,
  },
  {
    rating: 3,
    ratingCount: 0,
  },
  {
    rating: 2,
    ratingCount: 0,
  },
  {
    rating: 1,
    ratingCount: 0,
  },
];

export const reviews: Review[] = [
  {
    productImage: "/assets/product-image.png",
    productName: "Kucing Persia",
    productRating: 4,
    createdAt: new Date("2023-05-04"),
    buyerImage: "/assets/store-image.png",
    buyerName: "Angely",
    reviewContent: "testteste",
    satisfaction: "Sangat Puas",

    replies: [
      {
        isOwner: true,

        replyImage: "/assets/store-image.png",
        replyName: "SlivaPetStore",
        replyContent:
          "Terima kasih telah berbelanja di SlivaPetStore. Bagikan link toko kami https://www.slivadoc.com/slivashop/slivaPetStore kepada teman-teman kamu. Jangan lupa follow toko kami untuk tahu update terbaru tentang stok dan produk yang kami tawarkan.",
        createdAt: new Date(),
      },
    ],
  },
  {
    productImage: "/assets/product-image.png",
    productName: "Anjing Bulldog",
    productRating: 5,
    createdAt: new Date("2023-02-02"),
    buyerImage: "/assets/store-image.png",
    buyerName: "Koko Han",
    reviewContent: "testteste",
    satisfaction: "Sangat Puas",
    media:"https://images.unsplash.com/photo-1513350660342-816d92510adf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=833&q=80",
    replies: [
      {
        isOwner: true,
        replyImage: "/assets/store-image.png",
        replyName: "SlivaPetStore",
        replyContent: "testetetstetste",
        createdAt: new Date(),
      },
    ],
  },
  {
    productImage: "/assets/product-image.png",
    productName: "Anjing Shepherd",
    productRating: 3,
    createdAt:new Date("2023-04-05"),
    buyerImage: "/assets/store-image.png",
    buyerName: "Paijo",
    reviewContent: "testteste",
    satisfaction: "Sangat Puas",
    replies: [
      {
        isOwner: true,
        replyImage: "/assets/store-image.png",
        replyName: "SlivaPetStore",
        replyContent: "testetetstetste",
        createdAt: new Date(),
      },
    ],
  },
  {
    productImage: "/assets/product-image.png",
    productName: "Kucing Persia",
    productRating: 4,
    createdAt: new Date('2023-03-25'),
    buyerImage: "/assets/store-image.png",
    buyerName: "Angely",
    reviewContent: "testteste",
    satisfaction: "Sangat Puas",

    replies: [
      {
        isOwner: true,

        replyImage: "/assets/store-image.png",
        replyName: "SlivaPetStore",
        replyContent:
          "Terima kasih telah berbelanja di SlivaPetStore. Bagikan link toko kami https://www.slivadoc.com/slivashop/slivaPetStore kepada teman-teman kamu. Jangan lupa follow toko kami untuk tahu update terbaru tentang stok dan produk yang kami tawarkan.",
        createdAt: new Date(),
      },
    ],
  },
  {
    productImage: "/assets/product-image.png",
    productName: "Kucing Persia",
    productRating: 5,
    createdAt: new Date('2023-01-24'),
    buyerImage: "/assets/store-image.png",
    buyerName: "John Doyle",
    reviewContent: "testtttttt",
    satisfaction: "Sangat Puas",

    replies: [
      {
        isOwner: true,

        replyImage: "/assets/store-image.png",
        replyName: "SlivaPetStore",
        replyContent:
          "Terima kasih telah berbelanja di SlivaPetStore. Bagikan link toko kami https://www.slivadoc.com/slivashop/slivaPetStore kepada teman-teman kamu. Jangan lupa follow toko kami untuk tahu update terbaru tentang stok dan produk yang kami tawarkan.",
        createdAt: new Date(),
      },
    ],
  },
];
